### ISSUE TITLE
Unable to provision

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic-box#11]
On both my work and home desktop, I was not yet able to provision the VM successfully on the first try.

Every time `npm` will hang indefinitely until I have to Ctrl+C. Even with the latest version of Node/npm the problem persists.

This is with VirtualBox 4.3.14 (latest as of today) on Windows 7 x64.

**Comment by Ionitron** [comment]
Greetings @oliversalzburg!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
