### ISSUE TITLE
use ubuntu/trusty64

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic-box#15]
will the bootstrap.sh script work without any changes, if i use ```ubuntu/trusty64``` instead of ```ubuntu/trusty32``` on ```line 13```

**Comment by Crashthatch** [comment]
I tried it. It didn't install adb in /platform-tools, so the last 3 lines of bootstrap.sh failed. I'm sure there's a workaround, but I found it easier to switch to trusty32.

**Comment by Ionitron** [comment]
Greetings @programming-kid!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
