### ISSUE TITLE
No device

### ISSUE THREAD

**Issue by psimondk** [driftyco/ionic-box#16]
Was a bit lazy, so I tried the cloud build on a Linux Box (new ASUS rock based with all the trimmings) and no device shows up even though both the Nexus 7 and the Samsung S3 is in developer mode. Also tried the kill/start server

**Comment by Ionitron** [comment]
Greetings @psimondk!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
