### ISSUE TITLE
Genymotion emulator support?

### ISSUE THREAD

**Issue by seeshiv** [driftyco/ionic-box#17]
How can I use the Genymotion emulators with this? It doesn't recognize any connected devices or any emulators. Thanks

**Comment by camaleo** [comment]
using Ionic on OS X launch the "Genymotion Shell" and then:
ionic run android

**Comment by Ionitron** [comment]
Greetings @seeshiv!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
