### ISSUE TITLE
Login/Password

### ISSUE THREAD

**Issue by johntom** [driftyco/ionic-box#18]
Hi,
I'm testing ionic-box on a windows8.1 computer and have the login password showing up when I fire up the virtual box (ioinic-box_defailt_1411244920196_33904). Not sure how to proceed at this point.
TIA
John

**Comment by Ionitron** [comment]
Greetings @johntom!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
