### ISSUE TITLE
JAVA_HOME not set

### ISSUE THREAD

**Issue by mark-veenstra** [driftyco/ionic-box#19]
When I tried to add a platform with the command:
ionic platform add android

I got the error that the JAVA_HOME was not set. I can see in the bootstrap the JAVA_HOME hasn't been set. Could you please correct this?

**Comment by Ionitron** [comment]
Greetings @mark-veenstra!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
