### ISSUE TITLE
Add a synced-folder, so host can share development directory

### ISSUE THREAD

**Issue by somethingnew2-0** [driftyco/ionic-box#2]
```vagrant ssh``` is great for running ionic commands, but adding the development directory as synced-folder on the host by default may be easier for users running Sublime or Atom natively.

https://docs.vagrantup.com/v2/synced-folders/basic_usage.html

**Comment by Ionitron** [comment]
Greetings @somethingnew2-0!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
