### ISSUE TITLE
chown on ~/.android

### ISSUE THREAD

**Issue by jgallen23** [driftyco/ionic-box#20]
I wasn't able to get running until I changed the ownership of the ~/.android folder to vagrant:vagrant

**Comment by Ionitron** [comment]
Greetings @jgallen23!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
