### ISSUE TITLE
Error: An error occurred while listing Android targets

### ISSUE THREAD

**Issue by gremdev** [driftyco/ionic-box#26]
I got this error "Error: An error occurred while listing Android targets" when I use this command "ionic platform add android". 

How can I fix this?

**Comment by Ionitron** [comment]
Greetings @gremdev!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
