### ISSUE TITLE
ionic setup sass works but fails to run the gulp script

### ISSUE THREAD

**Issue by guyjacks** [driftyco/ionic-box#30]
http://pastebin.com/ticCpqXd

**Comment by davidkassa** [comment]
workaround sudo npm install -g gulp

**Comment by davidkassa** [comment]
not sure whether this is a problem with the box or whether the ionic npm package needs a dependency on gulp. I'm guessing the latter.

**Comment by Ionitron** [comment]
Greetings @guyjacks!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
