### ISSUE TITLE
updating to ionic cli 1.3.14 web page is not available

### ISSUE THREAD

**Issue by sgg90** [driftyco/ionic-box#41]
I have updated the ionic cli to 1.3.14 with the command:
sudo npm install -g ionic

And now i can't see my ionic app running with:
ionic serve --livereload

on 
http://localhost:8100

Has anyone the same problem? Any solution?

Thx

**Comment by NiltonCruz** [comment]
Same problem here...

**Comment by sgg90** [comment]
temporary solved returning to the previous version:

npm install -g ionic@1.3.11

**Comment by bradlund** [comment]
I also ran into this issue. Workaround: I edited my /home/vagrant/.ionic/ionic-config file to remove the ionicServerAddress line. The next time I ran ionic serve, rather than selecting "localhost", i selected the vagrant IP (10.0.2.15 in my case), and this worked.

The change was introduced in 1.3.13, when the address was added to app.listen() in this commit:
https://github.com/driftyco/ionic-cli/commit/6aa3371bb5a6eb3070addfd87820edde0a6c2a91#diff-dbd7ea9211336d11e4b9d5c3bd599fdc

previously, in the absence of a parameter, it was accepting connections on 0.0.0.0 aka any IPV4 address. 
https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback

**Comment by sgg90** [comment]
Thank you but it didn't worked

**Comment by Ionitron** [comment]
Greetings @sgg90!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
