### ISSUE TITLE
OpenSSL vulnerabilities reported by Google Play Store

### ISSUE THREAD

**Issue by sydneyhenrard** [driftyco/ionic-box#42]
I sign my app inside the ionic-box and uploaded it to the play store. I get a security alert:

>Security alert
Your app is statically linking against a version of OpenSSL that has multiple security vulnerabilities. You should update OpenSSL as soon as possible.
The vulnerabilities were addressed in OpenSSL versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. To confirm your OpenSSL version, you can do a grep via ("$ unzip -p YourApp.apk | strings | grep "OpenSSL""). For more information about the vulnerability, please consult http://www.openssl.org/news/secadv_20140605.txt.
To confirm that you've upgraded correctly, upload the updated version to the Developer Console and check back after five hours.
Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered "dangerous products" and subject to removal from Google Play.

I was wondering what I should do to fix that issue.

My signing script:

```
ionic build --release android 
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release/my-release-key.keystore ./platforms/android/build/outputs/apk/android-release-unsigned.apk alias_name
/home/vagrant/android-sdk-linux/build-tools/19.1.0/zipalign -v 4 ./platforms/android/build/outputs/apk/android-release-unsigned.apk release/MyRelease.apk
```

**Comment by Ionitron** [comment]
Greetings @sydneyhenrard!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
