### ISSUE TITLE
Android SDK outdated

### ISSUE THREAD

**Issue by gagustavo** [driftyco/ionic-box#43]
Android sdk version needs update

**Comment by quanghoc** [comment]
It's now faster to setup Android Studio and SDK on the Mac than using Ionic Box. Just MHO

What Ionic needs is an equivalent of Phonegap Build but for Ionic/Cordova and don't make people to modify config.xml (like Phonegap Build's).

**Comment by AgDude** [comment]
@mlynch any reason this is locked to a specific SDK version with the `filter` option?

**Comment by AgDude** [comment]
After installing a few, I see that the filter is probable intended to minimize the time to install.  So really the problem is that the sdk version is locked here in ionic-box, but `ionic start` doesn't specify a target, so it uses the latest. Either ionic should specify a target (in config.xml) or there should be some code in the bootstrap script which identifies the latest sdk used by cordova and installs that sdk version.
